### ISSUE TITLE
Add filter for author plugins and themes

### ISSUE THREAD

**Issue by hlashbrooke** [WebDevStudios/WP-Contributions#13]
It would be helpful to be able to filter the list of plugins returned by `wp_contributions_author_plugin_cards()`. The main reason for this is that if you originally authored a plugin that someone else has subsequently adopted, then it will still show up in your plugin list even though you no longer have anything to do with it. Adding a filter for this array will allow plugins to be dynamically removed.

While we're at it, I figured the same kind of filter for themes just makes sense too, but seeing as though I'm not a theme dev I'm not 100% sure how ownership works there.

Patch incoming :)

**Comment by dustyf** [comment]
Thanks!  Great idea.  Should be able to get this in the next release.
