### ISSUE TITLE
Update CSS for plugin card name top margin

### ISSUE THREAD

**Issue by robertdevore** [WebDevStudios/WP-Contributions#20]
I've been testing this plugin out with a couple different themes and I've noticed inconsistencies with the h5 tags used for the plugin titles in the widgets and shortcodes based on the theme's CSS for h5 tags.

It looks like there's CSS to adjust the bottom margin of the h5 `.plugin-card-name` class, but it doesn't update the top margin, which in some themes (seen in the [screenshots](https://github.com/WebDevStudios/WP-Contributions#screenshots)) causes it to not sit vertically flush with the thumbnail image.

I updated the CSS in a [fork](https://github.com/deviodigital/WP-Contributions) to fix this. I can issue a PR if/when its deemed important enough to add in but figured I'd open an issue first for discussion.

**Comment by colorful-tones** [comment]
I'll check this out soon, and seems like a plausible fix. Thanks.

**Comment by emilse-webdev** [comment]
Changing theme, twenty twenty-one 
![image](https://user-images.githubusercontent.com/104102110/174314975-2d8192f4-54b1-4ad5-a528-bb862046ccdb.png)

**Comment by tw2113** [comment]
I don't know right yet where that "breakpoint" will be, but at least for the 2 option screenshots above, I'd much prefer the icon be on top with all of the content below it. So I'd like to have us figure out where that break is at. I'd also like to put on a max size for the icon.

Extreme example, but I managed to have this below show up simply by having the widget in place, and pretty much full width content.

<img width="1005" alt="Screen Shot 2022-06-17 at 5 14 03 PM" src="https://user-images.githubusercontent.com/484075/174407558-72e011b6-0d84-4fd8-a273-ea4f84b7e8c8.png">

Definitely willing to do a bugfix for this part right now, but I also feel that our 20+ plugin users, over the past 6 years, could also probably patiently hold for a possible template/css revamp.

Less floating, more flexbox/grid and better overall markup.

**Comment by tw2113** [comment]
Some pending fixes in https://github.com/WebDevStudios/WP-Contributions/pull/27
