### ISSUE TITLE
I'd like to create a block for gutenberg for this plugin

### ISSUE THREAD

**Issue by emilse-webdev** [WebDevStudios/WP-Contributions#22]
It would be a great enhancement to add it anywhere on the site.
![image](https://user-images.githubusercontent.com/104102110/172425756-c9a112fb-667a-4058-9035-a07719a01bdd.png)

**Comment by emilse-webdev** [comment]
Works wonderful in widgets and as shortcode addition anywhere currently,

**Comment by tw2113** [comment]
Closed as merged in to release120 branch.
