### ISSUE TITLE
Add ability to show BuddyPress plugins, themes, codex, core contributions

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/WP-Contributions#4]
We love BuddyPress, and need to give it some love :heart: 

Lets add ability for user to show their BuddyPress activity as well. Anything to add here @tw2113 ?

**Comment by tw2113** [comment]
https://github.com/tw2113/buddypress-bbpress-contributions-list

**Comment by colorful-tones** [comment]
Would love to get this rolled in to WP Contributions, and will have to glean from @tw2113 's plugin.
