### ISSUE TITLE
Add WordCamp info: Attendance, Presenter, Volunteer, Organizer

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/WP-Contributions#5]
Allow users to have widget and template tags to show their WordCamp activity.

**Comment by hlashbrooke** [comment]
+1 to this - not sure how publicly available this info is, but it would be a great addition.

**Comment by iandunn** [comment]
@dustyf pinged me about this a couple weeks back, but unfortunately there isn't a good way to get that data from WordCamp.org yet. Here's my reply to him, just as an FYI for everyone else.

> On WordCamp.org, we have the raw data for speaking and organizing (if the organizers for the camp used the custom post types). We also have the raw data for attending, but only if the camp used the `require-login` addon for CampTix, and so far on SF 2014 and Belo Horizonte 2015 have done that.
>
> We don’t really have a good way of exposing that data via an API, though. The JSON API has the `/user` route on individual sites in a multisite, but it requires authentication, and it might not make sense to put data pulled from other sites there. It’d also be a very expensive query (searching all sites), but we could probably get around that with some caching. [#703-meta](https://meta.trac.wordpress.org/ticket/703) has some related discussion. We can customize it to show some minimal data to unauthenticated clients, but it’d require some thought and probably isn’t a high priority compared to other things.
>
> On Profiles, we have BuddyPress groups for speaking and organizing, and activity stream items for speaking, organizing and attending. (Of course, the same qualifiers apply as on WordCamp.org, the orgs have to use the CPTs and the require-login addon). On the front end the organizing group is lumped together with the community group, but they’re separate on the backend. There isn’t an API to expose any of that, but [#613-meta](https://meta.trac.wordpress.org/ticket/613) has some discussion on it. IIRC, we have data back to the beginning, but only the most recent X items are displayed.
