### ISSUE TITLE
Add documentation on theming

### ISSUE THREAD

**Issue by dustyf** [WebDevStudios/WP-Contributions#9]
Add documentation to the FAQ on creating templates in themes.

**Comment by colorful-tones** [comment]
I took a stab at updating the Readme to cover this: https://github.com/WebDevStudios/WP-Contributions/commit/6041e465e899887bfeb4f085aec3c422820827df

Think this is good for now?

**Comment by colorful-tones** [comment]
I'll have to update the readme.txt for .org too

**Comment by colorful-tones** [comment]
This should be resolved, and I'll push to .org repo shortly.

https://github.com/WebDevStudios/WP-Contributions/commit/aed15d2dc034112e94d7346d5dffa5c379f872c8
